language: csharp
mono: none
dotnet: 2.1.502
solution: BitmapNet.sln
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore
  - dotnet build
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
  - bash <(curl -s https://codecov.io/bash)
