language: csharp
mono: none
dotnet: 2.1.502
solution: BitmapNet.sln
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore
  - dotnet build
  - dotnet test BitmapNet.Test/BitmapNet.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="`pwd`/"
after_success:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "./coverage.opencover.xml"
